name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - name: winrar
      run: Invoke-WebRequest https://dl2.soft98.ir/soft/w/WinRAR.6.11.zip -OutFile winrar.zip
    - name: Xampp
      run: Invoke-WebRequest https://dl2.soft98.ir/soft/x-y-z/XAMPP.8.1.12.x64.rar -OutFile xampp.rar
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Download Flutter
      run: Invoke-WebRequest https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.3.9-stable.zip -OutFile flutter.zip
    - name: Extract flutter
      run: Expand-Archive flutter.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
      
